# Generated by Django 3.1 on 2020-08-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envios',
            old_name='tipo',
            new_name='departamento',
        ),
        migrations.AddField(
            model_name='envios',
            name='celular',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='envios',
            name='ciudad',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='envios',
            name='datos_adicionales',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='envios',
            name='direccion',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
