# Generated by Django 3.1 on 2020-08-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='token',
            field=models.CharField(default='', max_length=10000000),
        ),
    ]
