# Generated by Django 3.1 on 2020-08-18 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_auto_20200817_1354'),
        ('envios', '0002_auto_20200817_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='llega',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 11, 57, 47, 297616)),
        ),
        migrations.AlterField(
            model_name='envios',
            name='celular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='envios',
            name='ciudad',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='envios',
            name='datos_adicionales',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='envios',
            name='departamento',
            field=models.CharField(choices=[('Amazonas', 'Amazonas'), ('Antioquia', 'Antioquia'), ('Arauca', 'Arauca'), ('Atlántico', 'Atlántico'), ('Bogotá', 'Bogotá'), ('Bolívar', 'Bolívar'), ('Boyacá', 'Boyacá'), ('Caldas', 'Caldas'), ('Caquetá', 'Caquetá'), ('Casanare', 'Casanare'), ('Cauca', 'Cauca'), ('Cesar', 'Cesar'), ('Chocó', 'Chocó'), ('Córdoba', 'Córdoba'), ('Cundinamarca', 'Cundinamarca'), ('Guainía', 'Guainía'), ('Guaviare', 'Guaviare'), ('Huila', 'Huila'), ('La Guajira', 'La Guajira'), ('Magdalena', 'Magdalena'), ('Meta', 'Meta'), ('Nariño', 'Nariño'), ('Norte de Santander', 'Norte de Santander'), ('Putumayo', 'Putumayo'), ('Quindío', 'Quindío'), ('Risaralda', 'Risaralda'), ('San Andrés y Providencia', 'San Andrés y Providencia'), ('Santander', 'Santander'), ('Sucre', 'Sucre'), ('Tolima', 'Tolima'), ('Valle del Cauca', 'Valle del Cauca'), ('Vaupés', 'Vaupés'), ('Vichada', 'Vichada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='envios',
            name='direccion',
            field=models.CharField(max_length=10000),
        ),
        migrations.CreateModel(
            name='Item_enviado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.envios')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='principal.joya')),
            ],
        ),
    ]
