# Generated by Django 3.1 on 2020-08-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_envios_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='valor_total',
            field=models.IntegerField(default=16000),
        ),
    ]
