# Generated by Django 3.1 on 2020-08-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_envios_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envios',
            name='token',
        ),
        migrations.AddField(
            model_name='envios',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
