# Generated by Django 3.1 on 2020-08-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_auto_20200823_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='celular',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='envios',
            name='ciudad',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='envios',
            name='datos_adicionales',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='envios',
            name='departamento',
            field=models.CharField(choices=[('Amazonas', 'Amazonas'), ('Antioquia', 'Antioquia'), ('Arauca', 'Arauca'), ('Atlántico', 'Atlántico'), ('Bogotá', 'Bogotá'), ('Bolívar', 'Bolívar'), ('Boyacá', 'Boyacá'), ('Caldas', 'Caldas'), ('Caquetá', 'Caquetá'), ('Casanare', 'Casanare'), ('Cauca', 'Cauca'), ('Cesar', 'Cesar'), ('Chocó', 'Chocó'), ('Córdoba', 'Córdoba'), ('Cundinamarca', 'Cundinamarca'), ('Guainía', 'Guainía'), ('Guaviare', 'Guaviare'), ('Huila', 'Huila'), ('La Guajira', 'La Guajira'), ('Magdalena', 'Magdalena'), ('Meta', 'Meta'), ('Nariño', 'Nariño'), ('Norte de Santander', 'Norte de Santander'), ('Putumayo', 'Putumayo'), ('Quindío', 'Quindío'), ('Risaralda', 'Risaralda'), ('San Andrés y Providencia', 'San Andrés y Providencia'), ('Santander', 'Santander'), ('Sucre', 'Sucre'), ('Tolima', 'Tolima'), ('Valle del Cauca', 'Valle del Cauca'), ('Vaupés', 'Vaupés'), ('Vichada', 'Vichada')], max_length=500),
        ),
        migrations.AlterField(
            model_name='envios',
            name='direccion',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='envios',
            name='valor_total',
            field=models.IntegerField(default=16000000),
        ),
    ]
