# Generated by Django 3.1 on 2020-08-26 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0005_auto_20200826_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='fecha_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
