# Generated by Django 3.1 on 2020-08-21 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0005_auto_20200821_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='llega',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 10, 58, 22, 392817)),
        ),
    ]
