# Generated by Django 3.1 on 2020-08-21 10:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('envios', '0006_auto_20200821_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='llega',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 10, 58, 30, 354603)),
        ),
        migrations.AlterField(
            model_name='envios',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
