# Generated by Django 3.1 on 2020-09-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0006_envios_fecha_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='token',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='envios',
            name='valor_total',
            field=models.IntegerField(),
        ),
    ]
