# Generated by Django 3.1 on 2020-09-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0007_auto_20200906_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
