# Generated by Django 3.1 on 2020-10-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0008_auto_20200906_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_enviado',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
