# Generated by Django 3.1 on 2020-11-10 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
        ('envios', '0009_item_enviado_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_enviado',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='principal.joya'),
        ),
    ]
