# Generated by Django 3.1 on 2020-11-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0010_auto_20201110_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='estado',
            field=models.CharField(choices=[('Completado', 'Completado'), ('En envio', 'En envio'), ('Para entregar', 'Para Entregar'), ('Retrasado', 'Retrasado')], default='Para Entregar', max_length=500),
        ),
    ]
