# Generated by Django 3.1 on 2020-11-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0011_envios_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='estado',
            field=models.CharField(choices=[('Completado', 'Completado'), ('En envio', 'En envio'), ('Para entregar', 'Para entregar'), ('Retrasado', 'Retrasado')], default='Para entregar', max_length=500),
        ),
    ]
