# Generated by Django 3.1 on 2020-08-21 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out', models.BooleanField(default=False)),
                ('propietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Joya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100000)),
                ('material', models.CharField(choices=[('oro', 'Oro'), ('plata', 'Plata'), ('otros', 'Otros')], default='Oro', max_length=7)),
                ('tipo', models.CharField(choices=[('aretes', 'Arete'), ('pulseras', 'Pulsera'), ('collares', 'Collar'), ('anillos', 'Anillo'), ('otros', 'Otro')], default='Arete', max_length=50)),
                ('piedra', models.CharField(max_length=100000)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField(default=1)),
                ('vistas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.joya')),
            ],
        ),
    ]
