# Generated by Django 3.0.8 on 2020-08-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joya',
            name='tipo',
            field=models.CharField(default='Hola', max_length=10),
        ),
    ]
