# Generated by Django 3.0.8 on 2020-08-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_joya_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joya',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='joya',
            name='tipo',
        ),
        migrations.AddField(
            model_name='joya',
            name='material',
            field=models.CharField(choices=[('Oro', 'Oro'), ('Plata', 'Plata'), ('Otros', 'Otros')], default=2, max_length=7),
            preserve_default=False,
        ),
    ]
