# Generated by Django 3.1.4 on 2021-01-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20210114_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joya',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
