# Generated by Django 3.0.8 on 2020-08-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20200811_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joya',
            name='material',
            field=models.CharField(choices=[('Oro', 'Oro'), ('Plata', 'Plata'), ('Otros', 'Otros')], default='ORO', max_length=7),
        ),
    ]
