# Generated by Django 3.0.8 on 2020-08-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20200811_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joya',
            name='material',
            field=models.CharField(choices=[('oro', 'Oro'), ('plata', 'Plata'), ('otros', 'Otros')], default='ORO', max_length=7),
        ),
        migrations.AlterField(
            model_name='joya',
            name='tipo',
            field=models.CharField(choices=[('aretes', 'Arete'), ('pulseras', 'Pulsera'), ('collares', 'Collar'), ('anillos', 'Anillo'), ('otros', 'Otro')], default='Arete', max_length=50),
        ),
    ]
