# Generated by Django 3.0.8 on 2020-08-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20200811_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='joya',
            name='imagen',
            field=models.ImageField(default='logo.jpg', upload_to='static/images'),
        ),
    ]
