# Generated by Django 3.0.8 on 2020-08-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_joya_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='joya',
            name='descripcion',
            field=models.TextField(default='descripción'),
        ),
    ]
