# Generated by Django 3.0.8 on 2020-08-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_joya_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joya',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='joya',
            name='imagen',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='joya',
            name='piedra',
            field=models.CharField(max_length=100000),
        ),
    ]
