# Generated by Django 3.0.8 on 2020-08-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20200811_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='joya',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
