# Generated by Django 3.0.8 on 2020-08-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_joya_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joya',
            old_name='costo',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='joya',
            old_name='costo_currency',
            new_name='precio_currency',
        ),
    ]
