# Generated by Django 3.0.8 on 2020-08-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_auto_20200811_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joya',
            name='precio_currency',
        ),
        migrations.AlterField(
            model_name='joya',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
