# Generated by Django 3.0.8 on 2020-08-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20200811_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joya',
            name='imagen',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='static/images', width_field='width_field'),
        ),
    ]
