# Generated by Django 3.0.8 on 2020-08-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_carrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='propetario',
            new_name='propietario',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.AddField(
            model_name='carrito',
            name='check_out',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Joya')),
            ],
        ),
    ]
