# Generated by Django 3.0.8 on 2020-08-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_auto_20200812_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='joya',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
