# Generated by Django 3.1 on 2020-08-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_joya_vistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joya',
            name='material',
            field=models.CharField(choices=[('oro', 'Oro'), ('plata', 'Plata'), ('otros', 'Otros')], default='Oro', max_length=7),
        ),
    ]
